openapi: 3.0.0
info:
  title: Demo API
  description: A demo api to use in tests
  version: 1.0.0
paths:
  /users:
    get:
      summary: Returns a list of users.
      operationId: GetUsers
      responses:
        "200":
          description: A JSON array of user names.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example: ["Tim", "Tam"]
    post:
      summary: Create a user.
      operationId: CreateUser
      responses:
        "201":
          description: Returns the used id.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
